/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HundirLaFlota;

import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author cabdelda
 */
public class GUIHundirLaFlota extends javax.swing.JFrame {
//arraylist de barcos 1;
    //arraylist de barcos 2;
Tablero tableroJ1 = new Tablero();
Tablero tableroJ2 = new Tablero();
ArrayList<Barcos> listaBarcosJ1 = new ArrayList<>();
ArrayList<Barcos> listaBarcosJ2 = new ArrayList<>();

boolean ini = false;

    /**
     * Creates new form GUIHundirLaFlota
     */
    public GUIHundirLaFlota() {
        initComponents();
        tableroJ1.rellenarTablero();
        tableroJ2.rellenarTablero();
        //Tablero.rellenarTablero(tablero);
        setTitle("HUNDIR LA FLOTA");
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        visitante = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        local = new javax.swing.JTextPane();
        Boton2Jugadores = new javax.swing.JButton();
        IntroducirCoordenadas = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        Eventos = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Hundir la Flota");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jScrollPane3.setViewportView(visitante);

        jScrollPane4.setViewportView(local);

        Boton2Jugadores.setText("Empezar Partida");
        Boton2Jugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton2JugadoresActionPerformed(evt);
            }
        });

        IntroducirCoordenadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntroducirCoordenadasActionPerformed(evt);
            }
        });

        jButton1.setText("Introducir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportView(Eventos);

        jLabel2.setText("Introducir coordenadas en formato X,X");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(IntroducirCoordenadas, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Boton2Jugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(jLabel2)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Boton2Jugadores)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IntroducirCoordenadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(21, 21, 21))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void IniciarJuego(){
        
    }
    private void IntroducirCoordenadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntroducirCoordenadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IntroducirCoordenadasActionPerformed

    private void Boton2JugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton2JugadoresActionPerformed
        // TODO add your handling code here:
        local.setText("Jugador 1");
        visitante.setText("Jugador 2");
       jTextArea2.setText(tableroJ1.tableroAString());
       jTextArea1.setText(tableroJ2.tableroAString());
       String j1 = JOptionPane.showInputDialog("Introduce nombre del jugador 1");
       String j2 = JOptionPane.showInputDialog("Introduce nombre del jugador 2");
       local.setText(j1);
       visitante.setText(j2);

       int i = 0;
       String contenido = "";
       String[] t;
        while(i<8){
            
            switch(i) {
                case 0 :
                    contenido = JOptionPane.showInputDialog("Introduce coordenadas y orientación del portaaviones de "+ j1 + " (formato X,X,V/H)");
                    t=contenido.split(",");
                    Portaaviones p1 = new Portaaviones("Portaaviones-J1", 'P', parseInt(t[0]), parseInt(t[1]), false, (t[2].charAt(0) == 'v'));
                    while (!tableroJ1.introduccirBarco(p1)) {
                        contenido = JOptionPane.showInputDialog("Introduce coordenadas del portaaviones de "+ j1);
                        t=contenido.split(",");
                        p1 = new Portaaviones("Portaaviones-J1", 'P', parseInt(t[0]), parseInt(t[1]), false, (t[2].charAt(0) == 'v'));
                    }
                    jTextArea2.setText(tableroJ1.tableroAString());
                    listaBarcosJ1.add(p1);
                    i++;
                case 1 :
                    contenido = JOptionPane.showInputDialog("Introduce coordenadas del buque de "+ j1);
                    t=contenido.split(",");
                    Buque b1 = new Buque("Buque-J1", 'B', parseInt(t[0]), parseInt(t[1]), false, (t[2].charAt(0) == 'v'));           
                     while (!tableroJ1.introduccirBarco(b1)) {
                        contenido = JOptionPane.showInputDialog("Introduce coordenadas del buque de "+ j1);
                        t=contenido.split(",");
                        b1 = new Buque("Buque-J1", 'B', parseInt(t[0]), parseInt(t[1]), false, (t[2].charAt(0) == 'v'));
                    }
                     jTextArea2.setText(tableroJ1.tableroAString());
                     listaBarcosJ1.add(b1);
                     i++;
                case 2 :
                    contenido = JOptionPane.showInputDialog("Introduce coordenadas del submaarino de "+ j1);
                    t=contenido.split(",");
                    Submarino s1 = new Submarino ("Submarino-J1", 'S', parseInt(t[0]), parseInt(t[1]), false, (t[2].charAt(0) == 'v'));           
                     while (!tableroJ1.introduccirBarco(s1)) {
                        contenido = JOptionPane.showInputDialog("Introduce coordenadas del submaarino de "+ j1);
                        t=contenido.split(",");
                        s1 = new Submarino("Submarino-J1", 'S', parseInt(t[0]), parseInt(t[1]), false, (t[2].charAt(0) == 'v'));
                    }
                     jTextArea2.setText(tableroJ1.tableroAString());
                     listaBarcosJ1.add(s1);
                     i++;
                case 3 :
                    contenido = JOptionPane.showInputDialog("Introduce coordenadas de la Lancha de "+ j1);
                    t=contenido.split(",");
                    Lancha l1 = new Lancha ("Lancha-J1", 'P', parseInt(t[0]), parseInt(t[1]), false, (t[2].charAt(0) == 'v'));           
                     while (!tableroJ1.introduccirBarco(l1)) {
                        contenido = JOptionPane.showInputDialog("Introduce coordenadas de la Lancha de "+ j1);
                        t=contenido.split(",");
                        l1 = new Lancha("Lancha-J1", 'P', parseInt(t[0]), parseInt(t[1]), false, (t[2].charAt(0) == 'v'));
                    }
                     jTextArea2.setText(tableroJ1.tableroAString());
                     listaBarcosJ1.add(l1);
                     i++;
                case 4 :
                    contenido = JOptionPane.showInputDialog("Introduce coordenadas del portaaviones de "+ j2);
                    t=contenido.split(",");
                    Portaaviones p2 = new Portaaviones("Portaaviones-J2", 'P', parseInt(t[0]), parseInt(t[1]), false, (t[2].charAt(0) == 'v'));
                    
                    while (!tableroJ2.introduccirBarco(p2)) {
                        contenido = JOptionPane.showInputDialog("Introduce coordenadas del portaaviones de "+ j2);
                        t=contenido.split(",");
                        p2 = new Portaaviones("Portaaviones-J2", 'P', parseInt(t[0]), parseInt(t[1]), false, (t[2].charAt(0) == 'v'));
                    }
                    jTextArea1.setText(tableroJ2.tableroAString());
                    i++;
                    listaBarcosJ2.add(p2);
                case 5 :
                    contenido = JOptionPane.showInputDialog("Introduce coordenadas del buque de "+ j2);
                    t=contenido.split(",");
                    Buque b2 = new Buque("Buque-J2", 'B', parseInt(t[0]), parseInt(t[1]), false, (t[2].charAt(0) == 'v'));           
                     while (!tableroJ2.introduccirBarco(b2)) {
                        contenido = JOptionPane.showInputDialog("Introduce coordenadas del buque de "+ j2);
                        t=contenido.split(",");
                        b2 = new Buque("Buque-J2", 'B', parseInt(t[0]), parseInt(t[1]), false, (t[2].charAt(0) == 'v'));
                    }
                     jTextArea1.setText(tableroJ2.tableroAString());
                     listaBarcosJ2.add(b2);
                     i++;
                case 6 :
                    contenido = JOptionPane.showInputDialog("Introduce coordenadas del submaarino de "+ j2);
                    t=contenido.split(",");
                    Submarino s2 = new Submarino ("Submarino-J2", 'S', parseInt(t[0]), parseInt(t[1]), false, (t[2].charAt(0) == 'v'));           
                     while (!tableroJ2.introduccirBarco(s2)) {
                        contenido = JOptionPane.showInputDialog("Introduce coordenadas del submaarino de "+ j2);
                        t=contenido.split(",");
                        s2 = new Submarino("Submarino-J2", 'S', parseInt(t[0]), parseInt(t[1]), false, (t[2].charAt(0) == 'v'));
                    }
                     jTextArea1.setText(tableroJ2.tableroAString());
                     listaBarcosJ2.add(s2);
                     i++;
                case 7 :
                    contenido = JOptionPane.showInputDialog("Introduce coordenadas de la Lancha de "+ j2);
                    t=contenido.split(",");
                    Lancha l2 = new Lancha ("Lancha-J2", 'L', parseInt(t[0]), parseInt(t[1]), false, (t[2].charAt(0) == 'v'));           
                     while (!tableroJ2.introduccirBarco(l2)) {
                        contenido = JOptionPane.showInputDialog("Introduce coordenadas de la Lancha de "+ j2);
                        t=contenido.split(",");
                        l2 = new Lancha("Lancha-J2", 'P', parseInt(t[0]), parseInt(t[1]), false, (t[2].charAt(0) == 'v'));
                    }
                     jTextArea1.setText(tableroJ2.tableroAString());
                     listaBarcosJ2.add(l2);
                     i++;
            }

        }
        
        
       
       Eventos.setText("Turno Jugador 1");
    }//GEN-LAST:event_Boton2JugadoresActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String get = IntroducirCoordenadas.getText();
        String[] t=get.split(",");
        
        if (ini) {
            Eventos.setText("Turno Jugador 1");
            tableroJ1.actualizarMovimiento(Integer.parseInt(t[0]), Integer.parseInt(t[1]));
            jTextArea2.setText(tableroJ1.tableroAString());
            ini = false;
            IntroducirCoordenadas.setText("");
        } else {
            Eventos.setText("Turno Jugador 2");
            tableroJ2.actualizarMovimiento(Integer.parseInt(t[0]), Integer.parseInt(t[1]));
            jTextArea1.setText(tableroJ2.tableroAString());
            ini = true;
            IntroducirCoordenadas.setText("");
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIHundirLaFlota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIHundirLaFlota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIHundirLaFlota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIHundirLaFlota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIHundirLaFlota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton2Jugadores;
    private javax.swing.JTextPane Eventos;
    private javax.swing.JTextField IntroducirCoordenadas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextPane local;
    private javax.swing.JTextPane visitante;
    // End of variables declaration//GEN-END:variables
}
